# Generated by Django 2.2.12 on 2020-06-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20200609_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='requires_shipping',
            field=models.BooleanField(default=False, verbose_name='Requires shipping?'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='track_stock',
            field=models.BooleanField(default=False, verbose_name='Track stock levels?'),
        ),
    ]
