# Generated by Django 2.2.12 on 2020-06-12 10:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20200612_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=10, verbose_name='Correct Answer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True, verbose_name='Description'), blank=True, null=True, size=None),
        ),
    ]
