# Generated by Django 2.2.12 on 2020-07-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20200612_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_list',
        ),
        migrations.AlterField(
            model_name='product',
            name='structure',
            field=models.CharField(choices=[('standalone', 'Stand-alone product'), ('parent', 'Parent product'), ('child', 'Child product')], default='standalone', max_length=10, verbose_name='Product structure'),
        ),
    ]
