# Generated by Django 2.2.12 on 2020-07-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_quiz_quiztemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='product_class',
        ),
        migrations.AddField(
            model_name='quiz',
            name='product_class',
            field=models.ManyToManyField(blank=True, help_text='Choose what type of quiz this is', null=True, related_name='quiz', to='catalogue.ProductClass', verbose_name='Quiz type'),
        ),
    ]
