# Generated by Django 2.2.12 on 2020-07-11 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20200711_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='product_class',
        ),
        migrations.AddField(
            model_name='quiz',
            name='product_class',
            field=models.ForeignKey(blank=True, help_text='Choose what type of quiz this is', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz', to='catalogue.ProductClass', verbose_name='Quiz type'),
        ),
    ]
