# Generated by Django 2.2.12 on 2020-09-22 14:05

from django.db import migrations, models
import django.db.models.deletion
import oscar.models.fields.slugfield


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20200711_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('slug', oscar.models.fields.slugfield.SlugField(max_length=255, null=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'LanguageClass',
                'verbose_name_plural': 'LanguageClasses',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_template',
            field=models.ForeignKey(blank=True, help_text='Choose what template of quiz this is', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz_template', to='catalogue.QuizTemplate', verbose_name='Quiz type'),
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Question')),
                ('answers', models.TextField(blank=True, null=True, verbose_name='Answers')),
                ('correct_answer', models.TextField(blank=True, null=True, verbose_name='CorrectAnswer')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('publicity', models.BooleanField(default=True, help_text='This flag indicates if this questions can be public or not', verbose_name='Is publicable?')),
                ('difficulty', models.PositiveSmallIntegerField(db_index=True, default=3, help_text='Determine the difficulty of a question', verbose_name='Difficulty')),
                ('question_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_class', to='catalogue.LanguageClass', verbose_name='Question Class')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['date_updated'],
                'abstract': False,
            },
        ),
    ]
