# Generated by Django 2.2.12 on 2020-09-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_quiz_quiz_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'LanguageClass',
                'verbose_name_plural': 'LanguageClasses',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('quiz_class', models.ForeignKey(blank=True, help_text='Choose what language is this quiz on', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz_class', to='catalogue.LanguageClass', verbose_name='Quiz Class')),
            ],
            options={
                'verbose_name': 'QuizTopic',
                'verbose_name_plural': 'QuizzTopics',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Question')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Answer')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('publicity', models.BooleanField(default=True, help_text='This flag indicates if this questions can be public or not', verbose_name='Is publicable?')),
                ('difficulty', models.PositiveSmallIntegerField(db_index=True, default=3, help_text='Determine the difficulty of a question', verbose_name='Difficulty')),
                ('question_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_class', to='catalogue.LanguageClass', verbose_name='Question Class')),
                ('question_topic', models.ManyToManyField(to='catalogue.QuizTopic', verbose_name='Question Topic')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['date_updated'],
                'abstract': False,
            },
        ),
    ]
