# Generated by Django 2.2.12 on 2020-09-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20200922_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_class',
        ),
        migrations.AddField(
            model_name='questions',
            name='question_categories',
            field=models.ManyToManyField(to='catalogue.Category'),
        ),
    ]
