# Generated by Django 2.2.12 on 2020-11-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20200922_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['date_updated'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.CreateModel(
            name='QuestionsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Category', verbose_name='Category')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Questions', verbose_name='Questions')),
            ],
            options={
                'verbose_name': 'Questions category',
                'verbose_name_plural': 'Questions categories',
                'ordering': ['questions', 'category'],
                'abstract': False,
                'unique_together': {('questions', 'category')},
            },
        ),
    ]
