# Generated by Django 2.2.12 on 2020-09-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_languageclass_questions_quiztopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
        migrations.AddField(
            model_name='questions',
            name='answers',
            field=models.TextField(blank=True, null=True, verbose_name='Answers'),
        ),
        migrations.AddField(
            model_name='questions',
            name='correct_answer',
            field=models.TextField(blank=True, null=True, verbose_name='CorrectAnswer'),
        ),
    ]
